[build]
  publish = "."
  functions = "netlify/functions"

[dev]
  publish = "."
  functions = "netlify/functions"
  port = 8888


[[redirects]]
  from = "/api/ai"
  to = "/.netlify/functions/ai"
  status = 200